### ISSUE TITLE
请问可以提供接口，自定义布局，默认显示加载更多吗

### ISSUE THREAD

**Issue by krmao** [linfaxin/PullRefreshLoadRecyclerView#1]

**Comment by linfaxin** [comment]
使用 setLoadMoreView 方法设置自定义的LoadMoreView，需要实现的方法参考源码默认的DefaultLoadMoreView的实现。
使用loadmore.setIsAutoLoadWhenScroll(boolean autoload)控制滑倒底部时是否自动加载

**Comment by krmao** [comment]
慢慢细读楼主的代码，越发觉得楼主的牛逼。
纵观当前互联网能搜到的所有的上下拉Android刷新，没有一个有楼主的这种效果。
最接近QQ的下拉刷新，多指下拉，我也做了些修改，高仿QQ的，比如一次刷新成功，只要没有完全还原位移状态，不会进行第二次刷新。

当然，QQ的是重写的ListView 甚至 AdapterView

不过我依然好奇楼主的造诣为何如此至深，请问你是 熟读 Android 系统源代码？还是熟读 RecyclerView 源代码？或者是你是如何想到这种方法的呢？

再次感谢楼主，你这技术，我觉得进BAT 应该没有问题 ：）

**Comment by krmao** [comment]
我对楼主的代码如获至宝，并对楼主的开源精神钦佩有加，要像楼主学习和看齐。

**Comment by linfaxin** [comment]
:) 多看了源码的实现。

**Comment by krmao** [comment]
我一直以为做应用开发不需要研究系统源码，
楼主花在研究Android系统源码的精力，与收获成正比吗？
还是楼主本身就是系统工程师？
